FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true
RUN poetry install

COPY mng_api ./mng_api

CMD ["/app/.venv/bin/uvicorn", "mng_api.app:app", "--port", "5000"]
